### ISSUE TITLE
Indent Lines in the startup page

### ISSUE THREAD

**Issue by kusowl** [eoh-bse/minintro.nvim#3]
![Screenshot_20230711_080048](https://github.com/eoh-bse/minintro.nvim/assets/99195543/b3de9aa7-44c5-412f-a98a-c85ee253061f)
is there any way turnoff this indent lines ?
i am using indent-blankline by lukas-reineke for this lines.

**Comment by kusowl** [comment]
I fixed it by adding this line in my indent-blankline config
  filetype_exclude = {"minintro"},

**Comment by eoh-bse** [comment]
Thanks for raising an issue. `minintro` is simply texts on an uneditable and unsavable buffer. Whatever settings you have with other plugins will have an impact on the look of the intro screen.
Glad you were able to figure it out, and that's precisely the reason I added a file type to the buffer :)
